.circleci/config.yml
This PR adds CI using CircleCI.
Fixes #2.
=> Adds a circleci config

data/test-delete-reply.yml, data/test-delete-source.yml, data/test-delete-submission-from-string.yml, data/test-delete-submission.yml, data/test-download-reply.yml, data/test-download-submission.yml, data/test-error-unencrypted-reply.yml, data/test-failed-single-source.yml, data/test-flag-source.yml, data/test-get-all-replies.yml, data/test-get-all-submissions.yml, data/test-get-current-user.yml, data/test-get-replies-from-source.yml, data/test-get-reply-from-source.yml, data/test-get-single-source.yml, data/test-get-sources.yml, data/test-get-submission.yml, data/test-get-submissions.yml, data/test-get-wrong-submissions.yml, data/test-reply-source.yml, data/test-setup.yml, data/test-star-add-remove.yml, sdclientapi/__init__.py, tests/test_api.py
Fixes #4.
```
python -m unittest -v tests/test_api.py
```
I have also refreshed the vcr cassettes in the PR as there is a change in the values for sources.
=> Adds methods for reply endpoints

setup.py
Changes the name of the git repo/project.
=> Changes the name of the git repo

README.md
Signed-off-by: Vivek Anand <vivekanand1101@gmail.com>
=> readme: Remove line saying it isn't recommended project

sdclientapi/__init__.py
Signed-off-by: Vivek Anand <vivekanand1101@gmail.com>
=> Use urljoin instead of string concat for urls

CHANGELOG.md, setup.py
let's update PyPI with the latest code - what do you think @kushaldas?
=> securedrop-sdk 0.0.3

sdclientapi/__init__.py
=> fix #30: changed incorrect error msg when downloading a file

README.md
(Based on work done during 2018-11-12 documentation sprint
by @redshiftzero @conorsch @emkll @eloquence)
=> Update README with additional context

.circleci/config.yml, Makefile, Pipfile, README.md, setup.py
=> use `pipenv $cmd --keep-outdated` instead of locking all dependencies in the Pipfile

.circleci/config.yml, docs/development.rst
exactly what it says on the tin
=> updates how we call pipenv to ensure depenendencies aren't updated

CHANGELOG.md
fixes #58 
Only includes functional change, not CI or docs.
=> added changelog entries for 0.0.5 and 0.0.6

docs/development.rst
This contains steps on QubesOS about how to generate
test data for `test_apiproxy.py` file 🌈
``make html`` inside of the docs folder.
=> Adds docs on generating test data for APIProxy

setup.py
For bumping the version to `0.0.10` for a new release.
=> Getting ready for 0.0.10 release

.circleci/config.yml
See #98 for background.
Ready for review if/when CI passes
=> Bump server container timeout to 30m

setup.py
Updates the setup.py to 0.0.12 release.
I will push the source tarball to PyPI and also build the wheels for our mirror after this is merged.
=> Updates to 0.0.12 release

README.md
(for @creviera to look at when she gets a chance)
=> doc: explain how to pip install into virtualenv

CHANGELOG.md, setup.py
Towards #127 
Update config.py version number and add changelog
=> securedrop-sdk 0.1.1

data/test-download-submission.yml, data/test-setup.yml, tests/test_api.py
Fixes https://app.circleci.com/pipelines/github/freedomofpress/securedrop-sdk/178/workflows/b5c1aa45-8fa2-46a1-a83d-b72af964e684/jobs/1085
/cc @emkll
=> get first unread test submission

README.md
Replace old links and references to "master" with "HEAD" or "main"
=> update links and old references

requirements/dev-requirements.txt, requirements/requirements.txt
Updates to latest local wheel for idna.
=> update to idna 3.2 and dev deps

.circleci/config.yml
Clarify comments, update machine image & Dockerize version
=> Minor CI updates
