MANIFEST.in, setup.py
Now we can create sdists for pypi.org.
Fixes part of #3.
```
python setup.py sdist
```
The above command should create a source tarball.
=> Adds setup.py and a MANIFEST.in file

sdclientapi/__init__.py
Journalist users can change their usernames. This is why in the API we expose both current username and journalist uuid. 
For clients to keep the latest username updated, they need to access both the journalist username and the journalist uuid.
=> Add journalist UUID as attribute on Reply object

CHANGELOG.md, setup.py
* a second alpha release of this project, needed for https://github.com/freedomofpress/securedrop-client/pull/49
* adds changelog
Btw I noticed that the tag version and the version on PyPI are both 0.0.1, but we had 0.1.0 in `setup.py`, we should make sure that these are consistent going forward
=> securedrop-sdk 0.0.2

sdclientapi/__init__.py
On a Qubes system, execute the following code in Python (in the dev environment of sdk).
```
from sdclientapi import *
import pyotp
import sdclientapi
totp = pyotp.TOTP("JHCOGO7VCER3EJ4L")
username = "journalist"
password = "correct horse battery staple profanity oil chewy"
server = "http://localhost:8081/"
api = API(server, username, password, str(totp.now()), proxy=True)
api.authenticate()
try:
api.authenticate()
except sdclientapi.sdlocalobjects.BaseError:
print("Error in auth")
```
This should not print any big error messages on the `stderr`, only our `Error in auth` message should be printed'.
=> Fixes #37, get stderr text in our process in Qubes

sdclientapi/__init__.py
Since the proxyvm name is hardcoded in the sdk, we need to change the string to `sd-proxy` as part of https://github.com/freedomofpress/securedrop-workstation/issues/138
=> Rename sd-journalist to sd-proxy

CHANGELOG.md, setup.py
Release of latest securedrop-sdk changes to unblock renaming of sd-journalist to sd-proxy and the merging of the send replies functionality over in the client repository.
=> securedrop-sdk 0.0.4

.circleci/config.yml, Pipfile, Pipfile.lock
This will ensure pipenv lock command does not update package
versions unless explicitly specified in the Pipfile. Since we have automatic
security checks for vulnerabilities in python libraries, this will ensure more
consistency when building and testing our packages, and avoid drift in our requirements.txt and Pipfile.lock files.
=> Pin library versions in Pipfile

data/test-reply-source-with-uuid.yml, sdclientapi/__init__.py, tests/test_api.py
This is needed for the SDK to be able to set a reply's uuid so a client can track the state of an "in flight" reply in an asynchronous environment.
Related to https://github.com/freedomofpress/securedrop/issues/3957
Blocks https://github.com/freedomofpress/securedrop-client/issues/16
=> added optional client side uuid selection for replies

data/test-delete-reply.yml, data/test-delete-source.yml, data/test-delete-submission-from-string.yml, data/test-delete-submission.yml, data/test-download-reply.yml, data/test-download-submission.yml, data/test-error-unencrypted-reply.yml, data/test-failed-single-source.yml, data/test-flag-source.yml, data/test-get-all-replies.yml, data/test-get-all-submissions.yml, data/test-get-current-user.yml, data/test-get-replies-from-source.yml, data/test-get-reply-from-source.yml, data/test-get-single-source.yml, data/test-get-sources.yml, data/test-get-submission.yml, data/test-get-submissions.yml, data/test-get-wrong-submissions.yml, data/test-reply-source-with-uuid.yml, data/test-reply-source.yml, data/test-star-add-remove.yml, sdclientapi/__init__.py
Fixes #55
Note: The cassettes were updated with `sed` because this was a trivial change. To do some sort of confirmation, I recreated all of them to check that this actually works against the API and did a visual inspection of the diff to see that my change matches what was created.
=> Fix auth header to use "Token" and not "token"

.circleci/config.yml, .gitignore, Makefile, Pipfile, Pipfile.lock, sdclientapi/__init__.py, sdclientapi/sdlocalobjects.py, setup.cfg, tests/test_api.py, tests/test_apiproxy.py, tests/utils.py
fixes #62 
I also changed the `API` attribute `auth_headers` to `req_headers` because 2 of the 3 headers were not directly related to authorization.
I also split the received token from the API into two attributes `token:str` and `token_expiration:datetime` instead of leaving it as a `dict` since that makes type checking easier.
=> Added mypy and linting

.circleci/config.yml, Pipfile.lock, README.md, data/test-delete-reply.yml, data/test-delete-source.yml, data/test-delete-submission-from-string.yml, data/test-delete-submission.yml, data/test-download-reply.yml, data/test-download-submission.yml, data/test-error-unencrypted-reply.yml, data/test-failed-single-source.yml, data/test-flag-source.yml, data/test-get-all-replies.yml, data/test-get-all-submissions.yml, data/test-get-current-user.yml, data/test-get-replies-from-source.yml, data/test-get-reply-from-source.yml, data/test-get-single-source.yml, data/test-get-sources.yml, data/test-get-submission.yml, data/test-get-submissions.yml, data/test-get-wrong-submissions.yml, data/test-reply-source-with-uuid.yml, data/test-reply-source.yml, data/test-setup.yml, data/test-star-add-remove.yml, tests/test_api.py
the idea in this PR is to add a circle CI job that runs nightly and (I can be convinced the latter is a bad idea) on each PR. the circle CI job will run the API tests against the server container
that way if there's a discrepancy between API and SDK, we can detect it (ref: #55)
(btw I did this in a fork so that my frequent force pushing doesn't create a billion notifications)
=> ci: run SDK tests against latest version of API

.circleci/config.yml
fixes #66
This skips locking the dependencies in CI so we aren't only testing against one version of our dependencies when downstream consumers of this library might not pin to the same versions. This small amount of variance will help us catch bugs.
This also adds a change to how we call the unit test. We now use `make test` so it exactly matches the dev env. Additionally, we called `make check` for linting then `make test` to run the unit tests. However, `make check` has as a dependency the `test` target, so we were running the unit tests twice.
=> Skip locking of Pipenv in CI

README.md
=> [doc] SDK release guide

README.md, docs/development.rst, docs/index.rst, docs/install.rst
Towards #6
Also this trims the `README` and makes a note to the user to check the `docs` dir. We should avoid duplicating docs into multiple places where possible.
=> Extended dev docs

sdclientapi/__init__.py, tests/test_api.py, tests/test_apiproxy.py
Also adds tests for timeouts in `download_reply` and `download_submission` calls. 
Fixes #93
`make test` and also the steps mentioned in #93.
=> Fixes #93 raises the TimeOutErrors properly

sdclientapi/__init__.py, tests/test_api.py
(i figured I'd do this one so that we can make a new release of securedrop-sdk after this is merged with the other change we want for this sprint: https://github.com/freedomofpress/securedrop-sdk/pull/95)
Closes #86 
You can test interactively, or you can also just inspect the tests and existing test cassettes since the ETags headers are there in the requests/responses
=> expose ETag in submission/reply downloads

CHANGELOG.md, README.md, setup.py
We need this new SDK release to complete https://github.com/freedomofpress/securedrop-client/issues/383 and https://github.com/freedomofpress/securedrop-client/issues/384 for this sprint
This PR is step 4 in the securedrop-sdk release guide: https://github.com/freedomofpress/securedrop-sdk#releasing
=> securedrop-sdk 0.0.11

README.md
Qubes advises that all qrexec policy keywords should now begin with @ (instead of $).
For context, see the security bulletin here: https://github.com/QubesOS/qubes-secpack/blob/master/QSBs/qsb-038-2018.txt
=> Update qrexec policy keyword characters

sdclientapi/__init__.py, sdclientapi/sdlocalobjects.py, tests/test_apiproxy.py
Fixes #109 
Right now we have these status codes provided by the `securedrop-proxy` qrexec service: https://github.com/freedomofpress/securedrop-proxy/blob/21c2963ffb383092142bafdda6fd5886857b675d/securedrop_proxy/proxy.py#L263 and https://github.com/freedomofpress/securedrop-proxy/blob/21c2963ffb383092142bafdda6fd5886857b675d/securedrop_proxy/proxy.py#L270 which we should be passing through for clients to use. 
(btw, we _will_ probably treat a `ServerConnectionError` the same as a `RequestTimeoutError` from `securedrop-client`, but we shouldn't make them the same from the SDK since we might want to customize behavior later)
To test:
1. Run client on branch [use-sdk-serverconnectionerror](https://github.com/freedomofpress/securedrop-client/tree/use-sdk-serverconnectionerror)
2. Install …
=> fix 109, rework exception handling

CHANGELOG.md, setup.py
Also adds changelogs for `0.0.12` and the current release.
Closes #107
=> Updates to 0.0.13 release

CHANGELOG.md, README.md, setup.py
I'm preparing this release as we'll need to include it as a new dependency in `securedrop-client` for its next release.
I've tested it by using `master` of `securedrop-client` with this branch of the SDK and the latest nightly of `securedrop-proxy` (https://apt-test.freedom.press/pool/main/s/securedrop-proxy/securedrop-proxy_0.2.1-dev-20200427-060417%2Bbuster_all.deb). I've verified I can successfully sync with a staging server with 1000 sources and done basic network operations (sent a reply successfully, downloaded a file/message/reply successfully).
Once this is merged, I'll do the next steps which are: 
1. Push a tag signed with the release key
2. Upload the source tarball to PyPI
3. Upload the source tarball and wheel to our pip mirror
This also contains a change towards …
=> securedrop-sdk 0.1.0

CODE_OF_CONDUCT.md
Fix miswording in list of unacceptable behavior
The intent was clear but given the list is introduced as a list of behaviors people are expected to never engage into, the meaning was the opposite of the intention.
(authored by @gonzalo-bulnes, reviewed in https://github.com/freedomofpress/securedrop/pull/5372)
add mickael to CoC
(authored by @emkll, reviewed in https://github.com/freedomofpress/securedrop/pull/5405)
Restore language about choosing points of contact
(authored by @eloquence, review pending in https://github.com/freedomofpress/securedrop/pull/5439)
=> Incorporate recent updates to CoC

README.md
Closes #128 
Contains new instructions for `how to generate test data in Qubes`. I am wondering if I should modify the name of the vms too in this PR.
Go through the steps and see if you can generate new test data.
=> Updates README with better instructions for test data

README.md, tests/test_api.py, tests/utils.py
As part of working on #134 I noticed that `setUp` in `test_api.py` was not working as expected: when regenerating the cassette, authentication would either succeed, or it would fail and keep failing. The TOTP code was not successfully re-retrieved.
The logic does not work as currently written because 1) it would keep using the same TOTP code if it actually looped, which it doesn't because, 2) it will quietly exit the loop after sleeping.
Because we're already using a cassette to record the API response(s), there's really no reason for an additional utility method to stash and load it -- we just need to make sure we don't run sleeps when we're in playback mode.
Also fixes a path error for the RPC policy changes documented in the README.
Ready for review. CI will fail until #133 and #136 …
=> Fix TOTP retry logic, improve cassette handling; document

.circleci/config.yml
=> ci: run nightly job on default (main) branch

CHANGELOG.md, setup.py
Towards https://github.com/freedomofpress/securedrop-sdk/issues/141
=> securedrop-sdk 0.2.0

tests/test_api.py, tests/test_apiproxy.py, tests/test_shared.py
Resolves #67 (still some remaining room for improvement, but this takes care of the obvious duplication).
In addition to sub-classing from TestShared, I've refactored the `from_string` variants of the test. This is a good candidate for `pytest.mark.parametrize` for further light refactoring, but that [conflicts](https://stackoverflow.com/questions/18182251/does-pytest-parametrized-test-work-with-unittest-class-based-tests) with the current use of `unittest.TestCase`.
The other obvious area to refactor is the setup and teardown, but since those are in fact materially different between API and API proxy tests, that will be a somewhat bigger lift.
=> Move redundant code into shared test class

dev-requirements.in, dev-requirements.txt
Updates py to 1.10.0 to address CVE-2020-29651
Other changes should be limited to formatting output due to newer version of pip-tools
=> Update py to 1.10.0

CHANGELOG.md, setup.py
Time to cut a new release of the sdk so we can use the new /delete-conversation endpoint in the SecureDrop Client.
Towards https://github.com/freedomofpress/securedrop-sdk/issues/160
- Once this is merged, continue to work towards #160 via steps outlined here: https://github.com/freedomofpress/securedrop-sdk#releasing
=> Release securedrop-sdk 0.3.0

README.md
Once our `make venv` bug is fixed (see https://github.com/freedomofpress/securedrop-sdk/pull/162), this readme change can go in so that we make sure all devs are using the same developer setup instructions.
=> update readme for quicker quick start instructions

CHANGELOG.md, setup.py
Time to cut a new release of the sdk to include dependency updates.
=> Release securedrop-sdk 0.3.1

sdclientapi/__init__.py, sdclientapi/timestamps.py, tests/test_timestamps.py
Fixes #171 
Context https://github.com/freedomofpress/securedrop/issues/6257
=> Ensure support for common date string formats

CHANGELOG.md, setup.py
Time to cut a new release!
Towards https://github.com/freedomofpress/securedrop-sdk/issues/175
- Once this is merged, continue to work towards https://github.com/freedomofpress/securedrop-sdk/issues/175 via steps outlined here: https://github.com/freedomofpress/securedrop-sdk#releasing
=> Update version and changelog for securedrop-client 0.4.0

sdclientapi/__init__.py, sdclientapi/sdlocalobjects.py
Addresses: #94 
Allows Submissions and Replies to be retrieved by only their `uuid` and `source.uuid`
Tested against the client and development server using the following branch: https://github.com/nahara7/securedrop-client/tree/nahara/test-sdk and modifying the download call[ here](https://github.com/nahara7/securedrop-client/blob/c6959f36252e85bd44b14a8d6f15a375b6b259f2/securedrop_client/api_jobs/downloads.py#L257.) and[ here](https://github.com/nahara7/securedrop-client/blob/c6959f36252e85bd44b14a8d6f15a375b6b259f2/securedrop_client/api_jobs/downloads.py#L257.):
=> Update Fetching Sdk Objects

setup.cfg, setup.py
Not sure that this is really needed, but: since we only support sdk clients on bullseye, and because some dependencies (eg `requests`) have explicitly dropped support for python < 3.6, bump the python version in setup.cfg to 3.9 so it isn't confusing.
In the future, it would probably be better to look at getting rid of setup.cfg and specifying requires-python in the [[project] section of pyproject.toml](https://packaging.python.org/en/latest/specifications/declaring-project-metadata/#declaring-project-metadata).
**Test Plan**
=> Bump python version to 3.9

.circleci/config.yml
The tcp port is available as soon as the container is running, but we
actually want to wait for the HTTP server to be up, which means all the
Rust code has been built and sources generated. dockerize already
supports that, we just need to use the "http" protocol instead of "tcp".
This allows us to get rid of the manual "sleep 30" as well.
Fixes #183.
=> Have CI wait for HTTP to be up on server dev environment
